version: '3.3'

services:

  fastapi:
    build: ./services/fastapi
    command: uvicorn main:app --proxy-headers --reload --host 0.0.0.0 --port 5000
    ports:
      - 5000:5000
    # volumes:
    #   - ./services/fastapi:/app
    networks:
      - localhost

  nuxt3:
    build: ./services/nuxt3
    command: node .output/server/index.mjs
    ports:
      - 3000:3000
    # volumes:
    #   - ./services/nuxt3:/app
    networks:
      - localhost

  nginx:
    image: nginx:latest
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
    volumes:
      - ./services/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./services/certbot/conf:/etc/letsencrypt
      - ./services/certbot/www:/var/www/certbot
    depends_on:
      - fastapi
      - nuxt3
      - certbot
    networks:
      - localhost

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./services/certbot/conf:/etc/letsencrypt
      - ./services/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  localhost:
    driver: bridge