version: '3.3'

services:

  # fastapi:
  #   build: ./services/fastapi
  #   command: uvicorn main:app --proxy-headers --reload --host 0.0.0.0 --port 5000
  #   restart: unless-stopped
  #   ports:
  #     - 5000:5000
  #   # volumes:
  #   #   - ./services/fastapi:/app
  #   networks:
  #     - localhost

  # nuxt3:
  #   build: ./services/nuxt3
  #   command: node .output/server/index.mjs
  #   restart: unless-stopped
  #   ports:
  #     - 3000:3000
  #   # volumes:
  #   #   - ./services/nuxt3:/app
  #   networks:
  #     - localhost

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - localhost

  certbot:
    container_name: service_certbot
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

networks:
  localhost:
    driver: bridge