version: '3.3'

services:

  fastapi:
    build: ./services/fastapi
    command: uvicorn main:app --proxy-headers --reload --host 0.0.0.0 --port 5000
    ports:
      - 5000:5000
    # volumes:
    #   - ./services/fastapi:/app
    networks:
      - localhost

  nuxt3:
    build: ./services/nuxt3
    command: node .output/server/index.mjs
    ports:
      - 3000:3000
    # volumes:
    #   - ./services/nuxt3:/app
    networks:
      - localhost

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./services/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - localhost

networks:
  localhost:
    driver: bridge